%YAML 1.2
---
data_home: ~/Downloads/development-sample-21/raw-mimic/dev
processed_data_home: ./processed

collation_config: ./config/collation/clif-21.yaml
tokenization_config: ./config/tokenization/clif-21.yaml
